### ISSUE TITLE
如何训练获得KEG

### ISSUE THREAD

**Issue by LLLLLLoki** [MaoXinn/DATTI#1]
拜读了 您的论文发现方法很巧妙，现在我有自己的数据集想尝试一下论文中的方法，请问您可以将训练KEG的代码或者链接公开以下吗？

**Comment by MaoXinn** [comment]
我都是拿公开代码训练的呀，我github下面有我另一篇Dual-AMN的，其他的可能要你找一下他们的repo

--------------原始邮件--------------
发件人："LLLLLLoki ***@***.***&gt;;
发送时间：2022年8月11日(星期四) 下午2:34
收件人："MaoXinn/DATTI" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[MaoXinn/DATTI] 如何训练获得KEG (Issue #1)
-----------------------------------

 


拜读了 您的论文发现方法很巧妙，现在我有自己的数据集想尝试一下论文中的方法，请问您可以将训练KEG的代码或者链接公开以下吗？

**Comment by LLLLLLoki** [comment]
好的 ，感谢回答

**Comment by LLLLLLoki** [comment]
还有一个问题想请教以下，EA或者KEG入门的话有什么好推荐的吗？

**Comment by MaoXinn** [comment]
清华有个总结的paper list，叫entity alignment must read paper来着，总结的挺全的，你可以参考一下。

--------------原始邮件--------------
发件人："LLLLLLoki ***@***.***&gt;;
发送时间：2022年8月11日(星期四) 下午2:42
收件人："MaoXinn/DATTI" ***@***.***&gt;;
抄送："MaoXinn ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [MaoXinn/DATTI] 如何训练获得KEG (Issue #1)
-----------------------------------

 


还有一个问题想请教以下，EA或者KEG入门的话有什么好推荐的吗？
