### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by yangluheng** [MaoXinn/DATTI#2]
关注您的工作，这个代码可以不用DBP_ZH_EN/ent_emb.npy 跑吗

**Comment by MaoXinn** [comment]
可以啊，你想用什么算法生成的emb都可以的。
只要保证emb跟三元组中的实体和关系id是正确对应的即可。

**Comment by yangluheng** [comment]
您好，您的工作是必须使用预训练的嵌入吗，我看您的其他工作是随机初始化的

**Comment by MaoXinn** [comment]
是的，因为这只是个解码算法，不是可训练模型。
不过我昨天刚中了一篇emnlp，是非nn方法，可以不训练。过两天应该就放出来了，你可以关注一下。

--------------原始邮件--------------
发件人："yangluheng ***@***.***&gt;;
发送时间：2022年10月7日(星期五) 中午12:51
收件人："MaoXinn/DATTI" ***@***.***&gt;;
抄送："MaoXinn ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [MaoXinn/DATTI] 您好 (Issue #2)
-----------------------------------

 

 
您好，您的工作是必须使用预训练的嵌入吗，我看您的其他工作是随机初始化的

**Comment by yangluheng** [comment]
您好，关于您的工作RREA中，textual method 对齐结果用到了实体名称，但是您可以开源相应的代码吗，您目前开源的是没有用到实体名称的。另外，您最近中的emnlp 是否放出来了

发自我的iPhone

在 2022年10月7日，13:01，MaoXinn ***@***.***> 写道：

﻿

是的，因为这只是个解码算法，不是可训练模型。
不过我昨天刚中了一篇emnlp，是非nn方法，可以不训练。过两天应该就放出来了，你可以关注一下。

--------------原始邮件--------------
发件人："yangluheng ***@***.***&gt;;
发送时间：2022年10月7日(星期五) 中午12:51
收件人："MaoXinn/DATTI" ***@***.***&gt;;
抄送："MaoXinn ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [MaoXinn/DATTI] 您好 (Issue #2)
-----------------------------------




您好，您的工作是必须使用预训练的嵌入吗，我看您的其他工作是随机初始化的

**Comment by MaoXinn** [comment]
因为rrea的文本融合方法非常naive，就是单纯把词向量拼接上去，所以我没有放出来。
使用文本特征的可以参考我去年emnlp论文seu那个效果更好，还是无监督的。
今年的emnlp的话估计下周放出来吧，还在修改ing
--------------原始邮件--------------
发件人："yangluheng ***@***.***&gt;;
发送时间：2022年10月15日(星期六) 下午3:55
收件人："MaoXinn/DATTI" ***@***.***&gt;;
抄送："MaoXinn ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [MaoXinn/DATTI] 您好 (Issue #2)
-----------------------------------

 

 您好，关于您的工作RREA中，textual method 对齐结果用到了实体名称，但是您可以开源相应的代码吗，您目前开源的是没有用到实体名称的。另外，您最近中的emnlp 是否放出来了 
 
 发自我的iPhone 
 
 在 2022年10月7日，13:01，MaoXinn ***@***.***&gt; 写道： 
 
 ﻿ 
 
 是的，因为这只是个解码算法，不是可训练模型。 
 不过我昨天刚中了一篇emnlp，是非nn方法，可以不训练。过两天应该就放出来了，你可以关注一下。 
 
 --------------原始邮件-------------- 
 发件人："yangluheng ***@***.***&amp;gt;; 
 发送时间：2022年10月7日(星期五) 中午12:51 
 收件人："MaoXinn/DATTI" ***@***.***&amp;gt;; 
 抄送："MaoXinn ***@***.***&amp;gt;;"Comment ***@***.***&amp;gt;; 
 主题：Re: [MaoXinn/DATTI] 您好 (Issue #2) 
 ----------------------------------- 
 
 
 
 
 您好，您的工作是必须使用预训练的嵌入吗，我看您的其他工作是随机初始化的

**Comment by yangluheng** [comment]
感谢您的回复

发自我的iPhone

在 2022年10月15日，16:48，MaoXinn ***@***.***> 写道：

﻿

因为rrea的文本融合方法非常naive，就是单纯把词向量拼接上去，所以我没有放出来。
使用文本特征的可以参考我去年emnlp论文seu那个效果更好，还是无监督的。
今年的emnlp的话估计下周放出来吧，还在修改ing
--------------原始邮件--------------
发件人："yangluheng ***@***.***&gt;;
发送时间：2022年10月15日(星期六) 下午3:55
收件人："MaoXinn/DATTI" ***@***.***&gt;;
抄送："MaoXinn ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [MaoXinn/DATTI] 您好 (Issue #2)
-----------------------------------



您好，关于您的工作RREA中，textual method 对齐结果用到了实体名称，但是您可以开源相应的代码吗，您目前开源的是没有用到实体名称的。另外，您最近中的emnlp 是否放出来了

发自我的iPhone

在 2022年10月7日，13:01，MaoXinn ***@***.***&gt; 写道：

﻿

是的，因为这只是个解码算法，不是可训练模型。
不过我昨天刚中了一篇emnlp，是非nn方法，可以不训练。过两天应该就放出来了，你可以关注一下。

--------------原始邮件--------------
发件人："yangluheng ***@***.***&amp;gt;;
发送时间：2022年10月7日(星期五) 中午12:51
收件人："MaoXinn/DATTI" ***@***.***&amp;gt;;
抄送："MaoXinn ***@***.***&amp;gt;;"Comment ***@***.***&amp;gt;;
主题：Re: [MaoXinn/DATTI] 您好 (Issue #2)
-----------------------------------




您好，您的工作是必须使用预训练的嵌入吗，我看您的其他工作是随机初始化的
