### ISSUE TITLE
关于tensorly

### ISSUE THREAD

**Issue by kyleeea** [MaoXinn/DATTI#3]
您好，我在运行您的代码的时候，显示
AttributeError: module 'tensorly' has no attribute 'truncated_svd'
![image](https://user-images.githubusercontent.com/117267184/199663234-24676aad-0943-43fe-9418-c7deed3ce8da.png)
请问能否将代码
features = tensorly.truncated_svd(features,total_feature_size)[0]
替换为
features = tensorly.partial_svd(features,total_feature_size)[0]
替换后可以成功运行，当选择Dual_AMN，DBP_ZH_EN时
![image](https://user-images.githubusercontent.com/117267184/199662952-37c1b88a-cb92-40d0-97c2-961c0c8e2ed3.png)
hits@1 : 83.38% hits@10 : 95.14% MRR : 87.86%
结果与原文相差不多
但是当选择TransEdge，DBP_ZH_EN时
hits@1 : 79.89% hits@10 : 93.69% MRR : 84.96%
与原文有一定差距，这是因为这里修改的原因么

**Comment by MaoXinn** [comment]
不是的，注意看我Hyper-parameter那一节。
因为TransEdge的维度只有75，所以保留率reserve_ratio要调成20%。
这个参数在第三个block里面。

**Comment by kyleeea** [comment]
这里修改成tensorly.partial_svd是可以的么

**Comment by MaoXinn** [comment]
可以的吧，我记得我以前好像也用过这个api，应该是因为tensorly版本的问题。

**Comment by MaoXinn** [comment]
[](url)
